# Generated by Django 4.2.16 on 2024-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceivedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("alert", models.CharField(blank=True, max_length=255, null=True)),
                ("exchange", models.CharField(blank=True, max_length=255, null=True)),
                ("symbol", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
