# Generated by Django 4.2.16 on 2024-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhookapp", "0002_receivedrequest_strat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivedrequest",
            name="tradeReqId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
